// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo6HhbaDrNrOsLs-5kcCWULujml-1plaY',
    appId: '1:635921344671:web:6ad79307144b14a6a7daaa',
    messagingSenderId: '635921344671',
    projectId: 'albaterra-8f0bc',
    authDomain: 'albaterra-8f0bc.firebaseapp.com',
    databaseURL: 'https://albaterra-8f0bc-default-rtdb.firebaseio.com',
    storageBucket: 'albaterra-8f0bc.appspot.com',
    measurementId: 'G-SNVEYE2577',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjCPIHLfLRzv7CkdzeO6obSOw6njGwlGc',
    appId: '1:635921344671:android:d4b1a4d8ed39a16ba7daaa',
    messagingSenderId: '635921344671',
    projectId: 'albaterra-8f0bc',
    databaseURL: 'https://albaterra-8f0bc-default-rtdb.firebaseio.com',
    storageBucket: 'albaterra-8f0bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp7sBK99TxhGNECs6pP_5nf0R9SYNikvU',
    appId: '1:635921344671:ios:7ed8f4548ce65bc4a7daaa',
    messagingSenderId: '635921344671',
    projectId: 'albaterra-8f0bc',
    databaseURL: 'https://albaterra-8f0bc-default-rtdb.firebaseio.com',
    storageBucket: 'albaterra-8f0bc.appspot.com',
    iosClientId:
        '635921344671-bba8iit1850je41sj10p017bfgi0n1gk.apps.googleusercontent.com',
    iosBundleId: 'com.condalbaterra.albaterrapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp7sBK99TxhGNECs6pP_5nf0R9SYNikvU',
    appId: '1:635921344671:ios:7ed8f4548ce65bc4a7daaa',
    messagingSenderId: '635921344671',
    projectId: 'albaterra-8f0bc',
    databaseURL: 'https://albaterra-8f0bc-default-rtdb.firebaseio.com',
    storageBucket: 'albaterra-8f0bc.appspot.com',
    iosClientId:
        '635921344671-bba8iit1850je41sj10p017bfgi0n1gk.apps.googleusercontent.com',
    iosBundleId: 'com.condalbaterra.albaterrapp',
  );
}
